project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    background: primary
    right:
      - href: index.qmd
        text: Home
        icon: house
      - href: https://github.com/peculiar97
        text: GitHub
        icon: github
      - href: selectd_pub.qmd
        text: Selected Publications 
        icon: journal
      - href: https://www.instagram.com/araam_bsh/
        text: My Gallery
        icon: instagram
        
  page-footer: " Powered by Quarto"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-newwindow: true

editor: visual

